[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict"
]
build-backend = "setuptools.build_meta"


[project]
name = "o_voxel"
version = "0.0.1"
description = "All about voxel."
requires-python = ">=3.8"
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" }
]
dependencies = [
    "torch",
    "numpy",
    "plyfile",
    "trimesh",
    "tqdm",
    "zstandard",
    "easydict",
    "cumesh @ git+https://github.com/rwfsmith/CuMesh.git@44844ad5eea880d0a4218a7c99dbc44d1df33b67",
    "flex_gemm @ git+https://github.com/rwfsmith/FlexGEMM.git@c09f8e425e6a61edb7a209c5cc06f9f73254cde7",
]
